### ISSUE TITLE
[✨기능] 시야 리뷰 별점 기능

### ISSUE THREAD

**Issue by jihyunna** [SEE-NEMA/SEENEMA-backend#37]
## **✨ 구현 기능**
- 시야 리뷰 게시물 작성. 수정 시 별점 기능 추가

<br>

## **📢 To do**
- [x] 별도 엔티티  X , Dto에 항목 추가

**Comment by LaliMa-KJY** [comment]
post-theater은 tag가 삭제된 상태라서 post-theater2 새로 만들어서 작업하고  merge 후 삭제할게용
